# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/viva/myCPU/CPUfpga.cache/wt [current_project]
set_property parent.project_path D:/viva/myCPU/CPUfpga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/viva/myCPU/CPUfpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/bus.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/funct.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/opcode.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/segpos.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/pcdef.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/sim.v
}
set_property file_type "Verilog Header" [get_files D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/bus.v]
set_property file_type "Verilog Header" [get_files D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/funct.v]
set_property file_type "Verilog Header" [get_files D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/opcode.v]
set_property file_type "Verilog Header" [get_files D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/segpos.v]
set_property file_type "Verilog Header" [get_files D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/pcdef.v]
set_property file_type "Verilog Header" [get_files D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/include/sim.v]
read_verilog -library xil_defaultlib {
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Adder.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/BranchGen.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/core/Core.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/Counter.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/Digic_led.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/Digic_seg.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Divider/Divider.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Divider/Done_gate.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/EX.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/EXMEM.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/FunctGen.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/storage/HILO.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/storage/HILOReadProxy.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Hilo_Gen.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/ID.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/IDEX.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/if/IFID.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Logic.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/mem/MEM.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/mem/MEMWB.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/MemGen.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Multiplier/Multiplier.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Mux.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/OperandGen.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/if/PC.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/pipeline/PipelineController.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/pipeline/PipelineDeliver.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/sim/RAM.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/sim/ROM.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/storage/RegFile.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/id/RegGen.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/storage/RegReadProxy.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/Stall_btn.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/Switch_led.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/wb/WB.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/btn_out.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Divider/cas.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Divider/cas_row.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Multiplier/full_adder.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/mux_5to1.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/core/stage/ex/Multiplier/rca.v
  D:/viva/myCPU/CPUfpga.srcs/sources_1/imports/TINYCPU/fpga/Mycpu_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/viva/myCPU/CPUfpga.srcs/constrs_1/imports/fpga/digic_led.xdc
set_property used_in_implementation false [get_files D:/viva/myCPU/CPUfpga.srcs/constrs_1/imports/fpga/digic_led.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Mycpu_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Mycpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Mycpu_top_utilization_synth.rpt -pb Mycpu_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
